import '../models/models.dart';

/// Offline fallback data used when the network / backend is unavailable so
/// the UI is never empty. Dates are generated relative to "today".
class SampleData {
  SampleData._();

  static DateTime _d(int offsetDays) {
    final n = DateTime.now();
    return DateTime(n.year, n.month, n.day).add(Duration(days: offsetDays));
  }

  static List<Ipo> ipos() => [
        Ipo(
          id: 'sample-open-1',
          name: 'Bharat Renewables Ltd',
          symbol: 'BHARATREN',
          exchange: 'NSE, BSE',
          sector: 'Renewable Energy',
          openDate: _d(-1),
          closeDate: _d(1),
          allotmentDate: _d(2),
          listingDate: _d(4),
          priceMin: 285,
          priceMax: 300,
          lotSize: 50,
          issueSizeCr: 2400,
          registrar: 'Link Intime (MUFG Intime)',
          registrarUrl: 'https://linkintime.co.in/Initial_Offer/public-issues.html',
          about:
              'Independent power producer with 3.2 GW of operational solar and wind assets across Rajasthan, Gujarat and Karnataka. Proceeds fund 1.5 GW of new capacity and debt repayment.',
          subscriptionQib: 18.4,
          subscriptionNii: 22.1,
          subscriptionRetail: 6.8,
          gmp: 72,
        ),
        Ipo(
          id: 'sample-open-2',
          name: 'Zenith Fintech Services',
          symbol: 'ZENFIN',
          exchange: 'NSE, BSE',
          sector: 'Financial Services',
          openDate: _d(0),
          closeDate: _d(2),
          allotmentDate: _d(3),
          listingDate: _d(5),
          priceMin: 108,
          priceMax: 114,
          lotSize: 130,
          issueSizeCr: 860,
          registrar: 'KFin Technologies',
          registrarUrl: 'https://kosmic.kfintech.com/ipostatus/',
          about:
              'Digital lending and payments platform serving MSMEs in tier-2 and tier-3 cities with 4.1 million active merchants.',
          subscriptionQib: 4.2,
          subscriptionNii: 9.6,
          subscriptionRetail: 11.3,
          gmp: 18,
        ),
        Ipo(
          id: 'sample-up-1',
          name: 'Aarav Precision Components',
          symbol: 'AARAVPC',
          exchange: 'NSE SME',
          sector: 'Auto Ancillaries',
          openDate: _d(3),
          closeDate: _d(5),
          allotmentDate: _d(6),
          listingDate: _d(8),
          priceMin: 61,
          priceMax: 65,
          lotSize: 2000,
          issueSizeCr: 48,
          registrar: 'Bigshare Services',
          registrarUrl: 'https://ipo.bigshareonline.com/IPO_Status.html',
          about:
              'Manufacturer of precision-machined EV drivetrain components supplying to two-wheeler OEMs.',
          isSme: true,
          gmp: 12,
        ),
        Ipo(
          id: 'sample-up-2',
          name: 'MedVista Hospitals',
          symbol: 'MEDVISTA',
          exchange: 'NSE, BSE',
          sector: 'Healthcare',
          openDate: _d(6),
          closeDate: _d(8),
          allotmentDate: _d(9),
          listingDate: _d(11),
          priceMin: 640,
          priceMax: 672,
          lotSize: 22,
          issueSizeCr: 3100,
          registrar: 'Link Intime (MUFG Intime)',
          registrarUrl: 'https://linkintime.co.in/Initial_Offer/public-issues.html',
          about:
              'Multi-speciality hospital chain with 2,800 beds across 14 hospitals in South India.',
        ),
        Ipo(
          id: 'sample-closed-1',
          name: 'Nexora Logistics',
          symbol: 'NEXORA',
          exchange: 'NSE, BSE',
          sector: 'Logistics',
          openDate: _d(-5),
          closeDate: _d(-3),
          allotmentDate: _d(-2),
          listingDate: _d(1),
          priceMin: 210,
          priceMax: 221,
          lotSize: 67,
          issueSizeCr: 1250,
          registrar: 'KFin Technologies',
          registrarUrl: 'https://kosmic.kfintech.com/ipostatus/',
          about:
              'Integrated 3PL and express parcel operator with 220 hubs and a 9,000-vehicle fleet.',
          subscriptionQib: 61.2,
          subscriptionNii: 48.9,
          subscriptionRetail: 14.7,
          gmp: 55,
        ),
        Ipo(
          id: 'sample-listed-1',
          name: 'Suryakant Agro Foods',
          symbol: 'SURYAGRO',
          exchange: 'NSE, BSE',
          sector: 'FMCG',
          openDate: _d(-14),
          closeDate: _d(-12),
          allotmentDate: _d(-11),
          listingDate: _d(-9),
          priceMin: 150,
          priceMax: 158,
          lotSize: 94,
          issueSizeCr: 720,
          registrar: 'Link Intime (MUFG Intime)',
          registrarUrl: 'https://linkintime.co.in/Initial_Offer/public-issues.html',
          about: 'Branded staples and edible oil company with pan-India distribution.',
          subscriptionQib: 9.1,
          subscriptionNii: 12.3,
          subscriptionRetail: 5.6,
          gmp: 20,
          listingPrice: 181,
        ),
        Ipo(
          id: 'sample-listed-2',
          name: 'Quantum Semicon India',
          symbol: 'QSEMI',
          exchange: 'NSE, BSE',
          sector: 'Technology',
          openDate: _d(-22),
          closeDate: _d(-20),
          allotmentDate: _d(-19),
          listingDate: _d(-17),
          priceMin: 420,
          priceMax: 441,
          lotSize: 34,
          issueSizeCr: 5400,
          registrar: 'KFin Technologies',
          registrarUrl: 'https://kosmic.kfintech.com/ipostatus/',
          about: 'OSAT (outsourced semiconductor assembly & test) facility in Gujarat.',
          subscriptionQib: 112.4,
          subscriptionNii: 84.2,
          subscriptionRetail: 31.5,
          gmp: 190,
          listingPrice: 655,
        ),
      ];

  static List<MarketIndex> indices() => const [
        MarketIndex(
          name: 'NIFTY 50',
          exchange: 'NSE',
          last: 24812.35,
          change: 142.6,
          changePct: 0.58,
          open: 24690.1,
          high: 24855.0,
          low: 24640.2,
          previousClose: 24669.75,
          sparkline: [24670, 24700, 24688, 24740, 24790, 24760, 24830, 24812],
        ),
        MarketIndex(
          name: 'SENSEX',
          exchange: 'BSE',
          last: 81420.12,
          change: 455.8,
          changePct: 0.56,
          open: 81010.3,
          high: 81560.9,
          low: 80870.4,
          previousClose: 80964.32,
          sparkline: [80960, 81050, 81020, 81200, 81380, 81300, 81500, 81420],
        ),
        MarketIndex(
          name: 'NIFTY BANK',
          exchange: 'NSE',
          last: 51230.7,
          change: -128.4,
          changePct: -0.25,
          open: 51400.0,
          high: 51480.5,
          low: 51110.2,
          previousClose: 51359.1,
          sparkline: [51360, 51400, 51300, 51250, 51180, 51120, 51260, 51230],
        ),
        MarketIndex(
          name: 'NIFTY IT',
          exchange: 'NSE',
          last: 36540.2,
          change: 612.9,
          changePct: 1.71,
          open: 36000.0,
          high: 36600.0,
          low: 35950.5,
          previousClose: 35927.3,
          sparkline: [35930, 36050, 36120, 36300, 36420, 36380, 36560, 36540],
        ),
        MarketIndex(
          name: 'NIFTY MIDCAP 100',
          exchange: 'NSE',
          last: 57890.4,
          change: 210.3,
          changePct: 0.36,
          previousClose: 57680.1,
          sparkline: [57680, 57720, 57700, 57800, 57850, 57820, 57900, 57890],
        ),
        MarketIndex(
          name: 'INDIA VIX',
          exchange: 'NSE',
          last: 13.42,
          change: -0.61,
          changePct: -4.35,
          previousClose: 14.03,
          sparkline: [14.0, 13.9, 13.8, 13.6, 13.5, 13.55, 13.4, 13.42],
        ),
      ];

  static List<StockQuote> gainers() => const [
        StockQuote(symbol: 'INFY', name: 'Infosys', lastPrice: 1892.4, change: 61.2, changePct: 3.34, volume: 8120000, sector: 'IT'),
        StockQuote(symbol: 'TCS', name: 'Tata Consultancy Services', lastPrice: 4210.9, change: 118.5, changePct: 2.9, volume: 2450000, sector: 'IT'),
        StockQuote(symbol: 'ADANIPORTS', name: 'Adani Ports & SEZ', lastPrice: 1412.3, change: 36.8, changePct: 2.68, volume: 3120000, sector: 'Infrastructure'),
        StockQuote(symbol: 'TATAMOTORS', name: 'Tata Motors', lastPrice: 1024.6, change: 24.1, changePct: 2.41, volume: 9800000, sector: 'Auto'),
        StockQuote(symbol: 'HCLTECH', name: 'HCL Technologies', lastPrice: 1720.2, change: 38.4, changePct: 2.28, volume: 1900000, sector: 'IT'),
      ];

  static List<StockQuote> losers() => const [
        StockQuote(symbol: 'HDFCBANK', name: 'HDFC Bank', lastPrice: 1642.1, change: -28.4, changePct: -1.7, volume: 12400000, sector: 'Banking'),
        StockQuote(symbol: 'ICICIBANK', name: 'ICICI Bank', lastPrice: 1231.5, change: -18.2, changePct: -1.46, volume: 9100000, sector: 'Banking'),
        StockQuote(symbol: 'HINDUNILVR', name: 'Hindustan Unilever', lastPrice: 2510.8, change: -31.6, changePct: -1.24, volume: 1200000, sector: 'FMCG'),
        StockQuote(symbol: 'AXISBANK', name: 'Axis Bank', lastPrice: 1118.4, change: -12.9, changePct: -1.14, volume: 5600000, sector: 'Banking'),
        StockQuote(symbol: 'NESTLEIND', name: 'Nestle India', lastPrice: 2420.0, change: -22.5, changePct: -0.92, volume: 410000, sector: 'FMCG'),
      ];

  static List<NewsArticle> news() {
    final now = DateTime.now();
    return [
      NewsArticle(
        title: 'Nifty ends above 24,800 as IT stocks rally on strong US tech cues',
        link: 'https://economictimes.indiatimes.com/markets',
        source: 'Economic Times',
        publishedAt: now.subtract(const Duration(minutes: 35)),
        description: 'Benchmark indices closed higher for the third straight session led by Infosys, TCS and HCL Tech.',
      ),
      NewsArticle(
        title: 'Bharat Renewables IPO subscribed 15x on day two; GMP signals strong listing',
        link: 'https://www.moneycontrol.com/ipo',
        source: 'Moneycontrol',
        publishedAt: now.subtract(const Duration(hours: 2)),
        description: 'QIB portion booked 18 times while retail investors bid 6.8 times their quota.',
      ),
      NewsArticle(
        title: 'RBI keeps repo rate unchanged at 6.5%, maintains neutral stance',
        link: 'https://www.livemint.com/market',
        source: 'Livemint',
        publishedAt: now.subtract(const Duration(hours: 4)),
        description: 'The MPC voted 5-1 to keep policy rates on hold while trimming its inflation forecast.',
      ),
      NewsArticle(
        title: 'BSE launches new SME platform features to speed up listings',
        link: 'https://www.business-standard.com/markets',
        source: 'Business Standard',
        publishedAt: now.subtract(const Duration(hours: 6)),
      ),
      NewsArticle(
        title: 'FIIs turn net buyers after six weeks; pump Rs 3,200 crore into Indian equities',
        link: 'https://economictimes.indiatimes.com/markets/stocks',
        source: 'Economic Times',
        publishedAt: now.subtract(const Duration(hours: 9)),
      ),
    ];
  }

  static List<MarketIndex> globalIndices() => const [
        MarketIndex(name: 'S&P 500', exchange: 'USA', last: 5842.1, change: 31.2, changePct: 0.54, previousClose: 5810.9, sparkline: [5760, 5788, 5801, 5811, 5842]),
        MarketIndex(name: 'Dow Jones', exchange: 'USA', last: 42980.5, change: -85.3, changePct: -0.2, previousClose: 43065.8, sparkline: [43120, 43010, 43090, 43066, 42980]),
        MarketIndex(name: 'NASDAQ', exchange: 'USA', last: 18740.3, change: 188.6, changePct: 1.02, previousClose: 18551.7, sparkline: [18320, 18410, 18490, 18552, 18740]),
        MarketIndex(name: 'FTSE 100', exchange: 'UK', last: 8265.4, change: 12.7, changePct: 0.15, previousClose: 8252.7, sparkline: [8210, 8240, 8231, 8253, 8265]),
        MarketIndex(name: 'DAX', exchange: 'Germany', last: 19310.8, change: -64.2, changePct: -0.33, previousClose: 19375.0, sparkline: [19420, 19380, 19410, 19375, 19311]),
        MarketIndex(name: 'Nikkei 225', exchange: 'Japan', last: 38950.2, change: 412.5, changePct: 1.07, previousClose: 38537.7, sparkline: [38100, 38350, 38420, 38538, 38950]),
        MarketIndex(name: 'Hang Seng', exchange: 'Hong Kong', last: 20410.6, change: -210.4, changePct: -1.02, previousClose: 20621.0, sparkline: [20850, 20720, 20690, 20621, 20411]),
        MarketIndex(name: 'Shanghai Composite', exchange: 'China', last: 3312.4, change: 8.1, changePct: 0.25, previousClose: 3304.3, sparkline: [3280, 3295, 3290, 3304, 3312]),
        MarketIndex(name: 'Gold', exchange: 'Commodity', last: 2685.3, change: 14.8, changePct: 0.55, previousClose: 2670.5, sparkline: [2640, 2652, 2661, 2670, 2685]),
        MarketIndex(name: 'Crude Oil (WTI)', exchange: 'Commodity', last: 70.42, change: -1.15, changePct: -1.61, previousClose: 71.57, sparkline: [72.4, 72.1, 71.8, 71.57, 70.42]),
        MarketIndex(name: 'USD / INR', exchange: 'Forex', last: 84.12, change: 0.06, changePct: 0.07, previousClose: 84.06, sparkline: [83.95, 84.01, 84.05, 84.06, 84.12]),
      ];

  static List<StockQuote> globalStocks() => const [
        StockQuote(symbol: 'NVDA', name: 'NVIDIA', lastPrice: 138.2, change: 4.6, changePct: 3.44, volume: 245000000, sector: 'Semiconductors', currency: '\$', sparkline: [128, 131, 133.6, 133.6, 138.2]),
        StockQuote(symbol: 'AAPL', name: 'Apple', lastPrice: 229.5, change: 2.1, changePct: 0.92, volume: 52000000, sector: 'Technology', currency: '\$', sparkline: [225, 226.4, 227.1, 227.4, 229.5]),
        StockQuote(symbol: 'MSFT', name: 'Microsoft', lastPrice: 418.9, change: 3.4, changePct: 0.82, volume: 21000000, sector: 'Technology', currency: '\$', sparkline: [412, 414, 416.2, 415.5, 418.9]),
        StockQuote(symbol: 'GOOGL', name: 'Alphabet', lastPrice: 172.6, change: 1.2, changePct: 0.7, volume: 26000000, sector: 'Technology', currency: '\$', sparkline: [168, 169.5, 171, 171.4, 172.6]),
        StockQuote(symbol: 'AMZN', name: 'Amazon', lastPrice: 189.3, change: -0.8, changePct: -0.42, volume: 38000000, sector: 'Retail', currency: '\$', sparkline: [191, 190.2, 189.8, 190.1, 189.3]),
        StockQuote(symbol: 'META', name: 'Meta Platforms', lastPrice: 578.4, change: 6.9, changePct: 1.21, volume: 12000000, sector: 'Technology', currency: '\$', sparkline: [560, 565, 569, 571.5, 578.4]),
        StockQuote(symbol: 'TSLA', name: 'Tesla', lastPrice: 248.7, change: -9.4, changePct: -3.64, volume: 98000000, sector: 'Auto', currency: '\$', sparkline: [262, 259, 255, 258.1, 248.7]),
        StockQuote(symbol: 'JPM', name: 'JPMorgan Chase', lastPrice: 221.4, change: -2.6, changePct: -1.16, volume: 9000000, sector: 'Banking', currency: '\$', sparkline: [226, 225.1, 224.3, 224.0, 221.4]),
        StockQuote(symbol: 'XOM', name: 'Exxon Mobil', lastPrice: 117.8, change: -1.9, changePct: -1.59, volume: 15000000, sector: 'Energy', currency: '\$', sparkline: [121, 120.4, 119.9, 119.7, 117.8]),
        StockQuote(symbol: 'NFLX', name: 'Netflix', lastPrice: 762.1, change: 5.2, changePct: 0.69, volume: 3000000, sector: 'Media', currency: '\$', sparkline: [748, 752, 755, 756.9, 762.1]),
        StockQuote(symbol: 'TSM', name: 'Taiwan Semiconductor', lastPrice: 196.4, change: 3.8, changePct: 1.97, volume: 11000000, sector: 'Semiconductors', currency: '\$', sparkline: [188, 190, 192.5, 192.6, 196.4]),
        StockQuote(symbol: 'BABA', name: 'Alibaba', lastPrice: 98.6, change: -2.3, changePct: -2.28, volume: 22000000, sector: 'Retail', currency: '\$', sparkline: [104, 102.5, 101.2, 100.9, 98.6]),
      ];

  static List<NewsArticle> globalNews() {
    final now = DateTime.now();
    return [
      NewsArticle(
        title: 'Nasdaq hits record as chipmakers rally on strong AI demand',
        link: 'https://www.cnbc.com/markets/',
        source: 'CNBC',
        publishedAt: now.subtract(const Duration(minutes: 40)),
        description: 'NVIDIA and TSMC led gains after upbeat data-centre guidance; Treasury yields eased.',
      ),
      NewsArticle(
        title: 'Fed officials signal patience on rate cuts as inflation cools gradually',
        link: 'https://www.marketwatch.com/',
        source: 'MarketWatch',
        publishedAt: now.subtract(const Duration(hours: 2)),
        description: 'Markets now price two cuts this year; dollar index slips to a two-week low.',
      ),
      NewsArticle(
        title: 'Tesla slides 3% after deliveries miss estimates; analysts cut targets',
        link: 'https://finance.yahoo.com/',
        source: 'Yahoo Finance',
        publishedAt: now.subtract(const Duration(hours: 3)),
      ),
      NewsArticle(
        title: 'Oil falls as OPEC+ weighs output increase; Brent below \$75',
        link: 'https://www.investing.com/news/',
        source: 'Investing.com',
        publishedAt: now.subtract(const Duration(hours: 5)),
      ),
      NewsArticle(
        title: 'Hang Seng drops 1% as China stimulus hopes fade; Alibaba weak',
        link: 'https://www.cnbc.com/world-markets/',
        source: 'CNBC',
        publishedAt: now.subtract(const Duration(hours: 7)),
      ),
      NewsArticle(
        title: 'Nikkei climbs to one-month high on weaker yen and exporter gains',
        link: 'https://www.marketwatch.com/markets',
        source: 'MarketWatch',
        publishedAt: now.subtract(const Duration(hours: 9)),
      ),
    ];
  }
}
